<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div-Sites</name>
   <tag></tag>
   <elementGuidId>75e70b3c-e845-46ab-9b0b-3e5c8bee31b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.MuiTypography-root.MuiTypography-h4.css-1kbt94e</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'jakpost-01' or . = 'jakpost-01')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div[6]/div/div/div[3]/div[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>acf9ece6-4d65-463f-9996-a003e949b38f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTypography-root MuiTypography-h4 css-1kbt94e</value>
      <webElementGuid>2bb87cab-5a9d-4b33-8b17-815fca6fc0ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>jakpost-01</value>
      <webElementGuid>94d6d324-6932-4e3c-9030-c355a9c27803</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;MuiBox-root css-9zm725&quot;]/div[@class=&quot;MuiBox-root css-1u1t82v&quot;]/div[@class=&quot;MuiBox-root css-i9gxme&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-container MuiGrid-spacing-xs-2 css-dwhszv&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-item MuiGrid-grid-xs-12 MuiGrid-grid-md-4 css-14g76xw&quot;]/div[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-rounded MuiPaper-elevation1 MuiCard-root css-xbr6x6&quot;]/div[@class=&quot;MuiBox-root css-lw2yqf&quot;]/div[@class=&quot;MuiBox-root css-mitwe3&quot;]/div[@class=&quot;MuiBox-root css-kpfvhk&quot;]/div[@class=&quot;MuiTypography-root MuiTypography-h4 css-1kbt94e&quot;]</value>
      <webElementGuid>4268deb2-6a06-494f-8f56-630f46d7dc0d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div/div/div[3]/div/div/div/div[2]/div/div</value>
      <webElementGuid>d9078f4f-0315-4a07-b079-1f97f1b37f6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='STAGING'])[1]/following::div[3]</value>
      <webElementGuid>78ce728c-f6de-4804-8018-f92fe3eb0e9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='API Type'])[2]/following::div[10]</value>
      <webElementGuid>458c977f-7b91-4193-a398-02fb7a83f0f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='https://jakarta-post-api.vercel.app/api'])[1]/preceding::div[1]</value>
      <webElementGuid>b3fd5807-e7d9-44b0-a8e1-531419129dd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='API SCAN'])[1]/preceding::div[2]</value>
      <webElementGuid>a449c14f-c6a1-4b17-b1d2-d135e932a58b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='jakpost-01']/parent::*</value>
      <webElementGuid>e4f94a24-e80a-4888-8b62-688a5b712e5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[3]/div/div/div/div[2]/div/div</value>
      <webElementGuid>5d4834b5-fb86-4c23-a35d-78562b717d2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'jakpost-01' or . = 'jakpost-01')]</value>
      <webElementGuid>2df89f5c-7f64-43dd-9aed-edf5f87b0d1c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
