<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input-username</name>
   <tag></tag>
   <elementGuidId>3665abd9-77cd-487f-b576-5fe5735d45b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@placeholder = 'Search User...']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mui-165</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mui-165']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>04311d2d-d488-499d-8d37-66d97d884523</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d3ecd62b-a691-49b5-a560-a1a237084268</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search User...</value>
      <webElementGuid>f4fa272a-e580-4f57-95b7-e0d4817bcb85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1e4ce748-16c9-4c84-8bc3-39170fa57e14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputSizeSmall MuiInputBase-inputAdornedStart css-l26f1k</value>
      <webElementGuid>c7ff1c9c-e6c8-4d83-ad3e-1b703b0a11e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mui-165</value>
      <webElementGuid>baa76915-1885-46b8-946a-ddaff9647a34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mui-165&quot;)</value>
      <webElementGuid>33848660-7181-4253-b5e0-786bd143bd14</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mui-165']</value>
      <webElementGuid>280c633d-b990-46cb-add9-064f3deb85f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menu-']/div[3]/ul/li/div/div/div/input</value>
      <webElementGuid>f48cad4b-9ada-4a21-98a4-3c3b6b529643</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/div/div/input</value>
      <webElementGuid>a7f2b74e-efb3-427a-80c7-69ca962b2a57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Search User...' and @type = 'text' and @id = 'mui-165']</value>
      <webElementGuid>b355fade-0abd-4a69-adfa-c22443d8f6b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
