<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Div Profile</name>
   <tag></tag>
   <elementGuidId>bff221b0-0910-464b-930e-5ce50f95f7e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.MuiAvatar-img.css-1pqm26d-MuiAvatar-img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div[2]/div[2]/div/span/button/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>e65138cc-2da7-48c4-8cca-ee71ef3ba9b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/static/icon/userprofile.svg</value>
      <webElementGuid>b0a41deb-9804-4884-8ee0-0e42d8ba4c76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiAvatar-img css-1pqm26d-MuiAvatar-img</value>
      <webElementGuid>20f066ce-4495-420f-a587-d370832c1e6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-rounded MuiPaper-elevation1 MuiCard-root css-5093qw-MuiPaper-root-MuiCard-root&quot;]/div[@class=&quot;MuiBox-root css-70qvj9&quot;]/span[@class=&quot;MuiBox-root css-19fo97z&quot;]/button[@class=&quot;MuiButton-root MuiButton-text MuiButton-textSecondary MuiButton-sizeMedium MuiButton-textSizeMedium MuiButtonBase-root css-z6fduy-MuiButtonBase-root-MuiButton-root&quot;]/div[@class=&quot;MuiAvatar-root MuiAvatar-rounded css-fnt37w-MuiAvatar-root&quot;]/img[@class=&quot;MuiAvatar-img css-1pqm26d-MuiAvatar-img&quot;]</value>
      <webElementGuid>e44d8a9a-5712-4f92-8848-00974d83f60e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/span/button/div/img</value>
      <webElementGuid>208bac9f-f99e-4dd0-9c23-9a2ccbe4c85e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/div/img</value>
      <webElementGuid>0e16a52e-91b9-4d71-8536-62a6e1bade4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/static/icon/userprofile.svg']</value>
      <webElementGuid>dfc3d815-00f1-4148-a82c-af20a0ba257c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
