<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>RISK-ALL</name>
   <tag></tag>
   <elementGuidId>39f6f291-70bf-4616-bcd2-7aa489436de8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[3]/div[3]/ul/li[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>73e81a89-8baf-45e3-b3b5-33716aeefd7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1689656462670</value>
      <webElementGuid>1140974d-a3aa-4b61-9dc2-1b0965ad91bd</webElementGuid>
   </webElementProperties>
</WebElementEntity>
