<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input-Name-ruleName</name>
   <tag></tag>
   <elementGuidId>c032715b-4c66-4f1e-b7dd-ca5589e4bd58</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id = 'outlined-basic']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#outlined-basic</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='outlined-basic']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e9e84c4c-33a8-4ba5-9c72-b45c92442528</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6ca7e473-4eae-4f2d-aec1-d6a3fae5ff6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>outlined-basic</value>
      <webElementGuid>49876a35-6ab4-4939-97c1-29f8450eccfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ruleName</value>
      <webElementGuid>93124a28-c50f-4ca8-843d-96b8ff450bf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Input name of profile</value>
      <webElementGuid>d84fd8b3-e50d-4e18-8f3e-fba321460dd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ed1642d7-fb45-474d-b6d1-9986ea07e60a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputSizeSmall css-vyc9n8</value>
      <webElementGuid>9f96a574-3923-4d99-a36c-ce6c2869c6fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;outlined-basic&quot;)</value>
      <webElementGuid>d8b4749c-0109-463c-82b2-029f66ab186f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='outlined-basic']</value>
      <webElementGuid>da9506cd-36ff-406b-b2f3-0c5b31c4ce5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[6]/div/div/div/div[2]/div/div[2]/div/div/input</value>
      <webElementGuid>d38839d5-0bbe-4156-96f5-207e0ec302c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>9169d246-a56c-40b9-893b-ea8b9ef5f37d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'outlined-basic' and @type = 'text']</value>
      <webElementGuid>94b08327-0de2-403a-8c5d-4e10a08fa627</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='outlined-basic'])[2]</value>
      <webElementGuid>b26dc7f9-a656-4f91-91d6-690b243ec695</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>00a1010e-4f98-43f5-b48c-4aa0b4036726</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'outlined-basic' and @name = 'ruleName' and @placeholder = 'Input name of profile' and @type = 'text']</value>
      <webElementGuid>f3351f09-62b1-43e7-85de-ce566ad5965b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
