<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input-Name</name>
   <tag></tag>
   <elementGuidId>5a04386f-21ce-4dd9-96ca-f508dbbab6e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mui-60</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mui-60']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>771f959b-db50-4226-9a55-b70cf0aa5915</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>45f923b0-0c8c-4281-b7d3-e0606ab10344</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>name</value>
      <webElementGuid>8b483faa-5253-4056-98f3-025a9304aa88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Name for user</value>
      <webElementGuid>f4e00363-d343-4ff1-b650-0e1d8d759f34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9341d104-3389-48fb-9ea6-a810098f709a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputSizeSmall css-vyc9n8</value>
      <webElementGuid>532e9f74-f5fa-459a-84ce-b288c8f424e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mui-60</value>
      <webElementGuid>ec83aad7-ad41-42b5-a0f7-ebfcaea7133c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mui-60&quot;)</value>
      <webElementGuid>656c37ef-96d8-4d51-b4fe-da5d6c6a9327</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mui-60']</value>
      <webElementGuid>ca02fa62-9f28-4156-96d7-a62e773d034c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/input</value>
      <webElementGuid>a0b69e20-ef4a-4353-bf0b-5cb1836ef512</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'name' and @placeholder = 'Name for user' and @type = 'text' and @id = 'mui-60']</value>
      <webElementGuid>bb63b50f-e379-4ed8-a96c-418011a4b48e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
