<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input Branch Name</name>
   <tag></tag>
   <elementGuidId>feb267b8-dec8-407d-89c8-7e6a132d1878</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Use Custom Branch'])[1]/preceding::div[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@name = 'branch_name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mui-141</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d14dd6df-449a-419a-8802-a1bd0f65b011</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4776f5df-e654-4cbd-985d-aab082fd1194</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>3e26b70b-1f2d-4fd1-a158-9c88c9275c27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>branch_name</value>
      <webElementGuid>53a86090-4d2f-4205-8629-ca878b7053ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Custom Branch Name</value>
      <webElementGuid>f2423816-9f60-4e9d-b0ca-0e873cc0ed34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>41d4503c-fb35-457c-bd7f-14318b7b6127</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiOutlinedInput-input MuiInputBase-input MuiInputBase-inputSizeSmall css-7t4xrl-MuiInputBase-input-MuiOutlinedInput-input</value>
      <webElementGuid>97dd982f-e932-4e61-837e-2d9259514ee5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mui-141</value>
      <webElementGuid>c8131d80-b3d1-44a1-b178-e5fee3333d8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>mui-141-helper-text</value>
      <webElementGuid>dd10825f-5c65-4e33-8e1c-eae76a571a56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mui-141&quot;)</value>
      <webElementGuid>5f8e513e-c50c-429d-b822-0e35836246d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mui-141']</value>
      <webElementGuid>d3416194-2cb1-454d-8eb6-65fb32f21415</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/div/input</value>
      <webElementGuid>a379ba76-f7be-494b-b657-c87c6b58fc8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'branch_name' and @placeholder = 'Custom Branch Name' and @type = 'text' and @id = 'mui-141']</value>
      <webElementGuid>cc60f2b8-76e9-4109-9349-335d8a6f377f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
