<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input Token</name>
   <tag></tag>
   <elementGuidId>c654f9d9-cd18-4f99-adc9-40e2550265cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mui-47']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mui-47</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e5cd4efe-1fad-49cd-8ef0-39d9f745317d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7be1b0d9-4a88-450c-ac18-56c58a1fd4e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>git_pat</value>
      <webElementGuid>59776cf7-11a9-4be5-8a61-c1e031dddcc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Personal Access Token</value>
      <webElementGuid>e8cc3a40-6757-4308-806b-b14ab7e65c7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bd104b7b-c3cf-4776-9dd5-52d2437ad313</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiOutlinedInput-input MuiInputBase-input css-pb771q-MuiInputBase-input-MuiOutlinedInput-input</value>
      <webElementGuid>555a9108-39de-4e50-af0c-d43dec89837c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mui-47</value>
      <webElementGuid>cefd9df8-235e-498b-ad0b-14feed7b4831</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mui-47&quot;)</value>
      <webElementGuid>20a0fcc3-95da-4f74-90d4-c80c9f87a7bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mui-47']</value>
      <webElementGuid>1c5124a4-4e42-43fd-9633-b8b7793e4017</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div/div/div/input</value>
      <webElementGuid>93adb733-e289-4708-b5f8-af8a1e036a37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'git_pat' and @placeholder = 'Personal Access Token' and @type = 'text' and @id = 'mui-47']</value>
      <webElementGuid>6d918ec2-0f56-4c00-b4c0-06835d7c3b24</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
