<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button How can you fix it</name>
   <tag></tag>
   <elementGuidId>a70e7c7c-927d-48e8-bc91-3b9ab152e6b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[64]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>62a172fc-2ea1-4e8d-882f-2de948a35776</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiButtonBase-root MuiTab-root MuiTab-textColorPrimary css-1oyq3kt-MuiButtonBase-root-MuiTab-root</value>
      <webElementGuid>abc212a9-4479-4f59-82ba-efeeb31ee72e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>560ac407-80bf-468a-aabe-d6138994e6a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>36c565d9-457f-4b39-91da-2816388ef3a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>eeafd4c3-ebca-4268-bd20-4438949e5585</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>06a608cf-b500-4bcf-9e5e-2762463dca83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>How can you fix it?</value>
      <webElementGuid>016aebcb-c949-4cfb-8690-141f26468249</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;MuiBox-root css-9zm725&quot;]/div[@class=&quot;MuiBox-root css-1u1t82v&quot;]/div[@class=&quot;MuiBox-root css-i9gxme&quot;]/div[@class=&quot;MuiBox-root css-1l5ydl0&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-container MuiGrid-spacing-xs-2 css-17240zl-MuiGrid-root&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-item MuiGrid-grid-xs-12 MuiGrid-grid-md-8 css-15g7r7r-MuiGrid-root&quot;]/div[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-rounded MuiPaper-elevation1 MuiCard-root css-vts97k-MuiPaper-root-MuiCard-root&quot;]/div[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-rounded MuiPaper-elevation1 MuiCard-root css-z0iqim-MuiPaper-root-MuiCard-root&quot;]/div[@class=&quot;MuiCardContent-root css-1feuc5z-MuiCardContent-root&quot;]/div[@class=&quot;MuiTabs-root css-s3gjr6-MuiTabs-root&quot;]/div[@class=&quot;MuiTabs-scroller MuiTabs-hideScrollbar MuiTabs-scrollableX css-1iev5os-MuiTabs-scroller&quot;]/div[@class=&quot;MuiTabs-flexContainer css-1pyy021-MuiTabs-flexContainer&quot;]/button[@class=&quot;MuiButtonBase-root MuiTab-root MuiTab-textColorPrimary css-1oyq3kt-MuiButtonBase-root-MuiTab-root&quot;]</value>
      <webElementGuid>7f6b43e3-e1a6-43d0-aba1-00845fdab2a2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[64]</value>
      <webElementGuid>fd4c4533-e898-4722-ae2f-ab0b98b2ba83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div/div/div/div[2]/div[2]/div/div[4]/div[2]/div/div[2]/div/button[3]</value>
      <webElementGuid>31dab5a5-878a-49de-9854-1cb2304dab00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Are you at risk?'])[1]/following::button[1]</value>
      <webElementGuid>55620976-0ad4-467e-a57d-2d3800797468</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('what', &quot;'&quot;, 's the risk?')])[1]/following::button[2]</value>
      <webElementGuid>7683779c-6444-4088-a1ab-141b196b5d47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Exceptions'])[1]/preceding::button[1]</value>
      <webElementGuid>48af18b0-0f23-4b09-a550-c963be86051e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*Bold* ``Code`` * Bulleted point'])[1]/preceding::button[1]</value>
      <webElementGuid>b454f9d1-904b-4389-9099-1e3bd4ade799</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='How can you fix it?']/parent::*</value>
      <webElementGuid>c82cb3fc-5b26-4d12-bafa-8334e3320807</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[3]</value>
      <webElementGuid>558cc425-47da-4b99-8eb6-1d9a59fe10eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'How can you fix it?' or . = 'How can you fix it?')]</value>
      <webElementGuid>8b0eaa80-f817-4c69-b51f-eb1283bdc44c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
