<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>example</name>
   <tag></tag>
   <elementGuidId>0f31f775-8b2b-4553-958c-de4731fdffda</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>[data-testid='CheckBoxIcon']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Select the secret result :'])[1]/following::div[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>0622903e-5926-4ee8-8b13-fc603ee6c563</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>[data-testid='CheckBoxIcon']</value>
      <webElementGuid>3e83ffb6-11d7-4614-a1f5-e8f5851c1d02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiList-root MuiList-padding css-aksuhv</value>
      <webElementGuid>ce20cc3b-9d68-461d-8b99-f2d533f36a43</webElementGuid>
   </webElementProperties>
</WebElementEntity>
