<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input-sitename</name>
   <tag></tag>
   <elementGuidId>1b27396c-7b24-4efb-b8c6-78049f3f0ed4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mui-116</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@placeholder = 'Input Site Name']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div[6]/div/div/div[2]/div[2]/div[3]/div[2]/div[3]/div/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>53c0b438-6a4e-446e-8d11-9e027ddc12ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4e9a84d6-1d66-4631-a4ff-965114e654dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>sitename</value>
      <webElementGuid>9e3cb998-d479-4a52-a89b-e596cd7ad990</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Input Site Name</value>
      <webElementGuid>29153c1e-bbfb-4a99-8393-e241f48bc0fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>872d2299-f641-4413-a75f-968def77c44d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input css-1e8usrf</value>
      <webElementGuid>6e3fb4c1-c3c2-4cf2-b5fd-b07f204d05eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mui-116</value>
      <webElementGuid>d5fc311f-acba-49e2-a367-15db592bff59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mui-116&quot;)</value>
      <webElementGuid>ea491fc8-06a5-4bac-ad35-ee4541b073ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mui-116']</value>
      <webElementGuid>56a9533b-317e-46b7-94ec-6c09504db4eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[6]/div/div/div[2]/div/div[2]/div[2]/div[3]/div/div/input</value>
      <webElementGuid>420b7362-8b5f-4968-a288-f3cd32909072</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
      <webElementGuid>910bda4b-e6a9-45dc-9257-75848cf246af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'sitename' and @placeholder = 'Input Site Name' and @type = 'text' and @id = 'mui-116']</value>
      <webElementGuid>d022f33a-eb0c-4b3a-9c43-dbc7674d08a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
