<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input-sitenameAPI</name>
   <tag></tag>
   <elementGuidId>3efd35af-f4db-4518-8875-1e0c7e2a8b0b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mui-116</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div[6]/div/div/div[2]/div[2]/div[3]/div[2]/div[3]/div/div/input</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@placeholder = 'Input Site Name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>52794e6a-22f5-4012-8125-f9f33de5e564</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>402b8e6e-1fc4-4ad1-9579-1519a9efe34b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>sitename</value>
      <webElementGuid>242f534d-a70d-4449-8bde-5beefe2daa0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Input Site Name</value>
      <webElementGuid>f1767a4e-6292-45cd-8ce7-8d4c0728741f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>179891a0-8e4c-4787-a4f8-0a4ae6d402de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input css-1e8usrf</value>
      <webElementGuid>fcf7f311-96f8-41c4-a82d-7e3fb498df30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mui-116</value>
      <webElementGuid>990f212b-759d-49a1-9744-a9fa02ad1eee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mui-116&quot;)</value>
      <webElementGuid>5aec92ef-5622-499c-8020-ff9f6e6b3a10</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mui-116']</value>
      <webElementGuid>2d86510f-f2e2-4200-bd01-694ac0b772e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[6]/div/div/div[2]/div/div[2]/div[2]/div[3]/div/div/input</value>
      <webElementGuid>dc04214c-49ac-4192-a071-7d126340da49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
      <webElementGuid>861ff0b9-c3f2-4f9b-8179-7f61161fd2c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'sitename' and @placeholder = 'Input Site Name' and @type = 'text' and @id = 'mui-116']</value>
      <webElementGuid>eb7fd74e-8bee-4af6-9c9d-3ce0fbb356b2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
