<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button-SiteScan</name>
   <tag></tag>
   <elementGuidId>8b4020e3-6d81-43a0-b02e-0449250c0f43</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[19]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>264a803a-ea6e-47e9-85a4-62d0911ab16a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiButtonBase-root MuiButton-root MuiButton-text MuiButton-textPrimary MuiButton-sizeMedium MuiButton-textSizeMedium MuiButton-root MuiButton-text MuiButton-textPrimary MuiButton-sizeMedium MuiButton-textSizeMedium  css-14av6cr</value>
      <webElementGuid>b3f00c3d-9279-4f3b-b70e-6a707f143cb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>9e9d0900-4be7-4f52-a6f2-5595200bd6c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>18138978-c2c6-4b9d-af8a-144ea1805166</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Site Scan</value>
      <webElementGuid>c227a863-84d3-41e6-bec4-bbbe5afab980</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;MuiBox-root css-jofdb2&quot;]/div[1]/div[1]/div[@class=&quot;MuiBox-root css-1rc5hnf&quot;]/div[@class=&quot;MuiList-root MuiList-padding MuiList-subheader css-z47oi3&quot;]/div[@class=&quot;MuiBox-root css-1v2ma4q&quot;]/div[@class=&quot;MuiList-root MuiList-padding css-1gq77i3&quot;]/div[@class=&quot;MuiListItem-root MuiListItem-gutters MuiListItem-padding css-1xbwt53&quot;]/button[@class=&quot;MuiButtonBase-root MuiButton-root MuiButton-text MuiButton-textPrimary MuiButton-sizeMedium MuiButton-textSizeMedium MuiButton-root MuiButton-text MuiButton-textPrimary MuiButton-sizeMedium MuiButton-textSizeMedium  css-14av6cr&quot;]</value>
      <webElementGuid>f14ef32e-360c-4bdb-94c4-c8d49168edc4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[19]</value>
      <webElementGuid>8c4bfef5-c4c1-4e2f-b642-d1bfd9766e82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div/div[4]/div/div[2]/div/div/button</value>
      <webElementGuid>d1eb587f-de9f-40e3-9b8a-a71806cc36a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dynamic Security'])[1]/following::button[1]</value>
      <webElementGuid>72380ae9-93b5-4f03-b678-4d38fb44099e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Misconf Repository'])[1]/following::button[1]</value>
      <webElementGuid>2beb6fa9-be65-4850-a89a-ec1244d21e11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Scan History'])[1]/preceding::button[1]</value>
      <webElementGuid>99da6e88-5c8d-4485-a298-fb4c68dcedd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mobile Security'])[1]/preceding::button[2]</value>
      <webElementGuid>41c7f9f7-f704-4ed1-b179-75a5627a1599</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Site Scan']/parent::*</value>
      <webElementGuid>b29bd278-b5a8-481a-bb59-be494ce2aef7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/div/div/button</value>
      <webElementGuid>a62cd90f-c010-4497-991b-35068d765d86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Site Scan' or . = 'Site Scan')]</value>
      <webElementGuid>0202edc0-0d11-42d9-90d3-a9407a52887a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
