<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input repo-url update</name>
   <tag></tag>
   <elementGuidId>84a27ed7-e222-4152-a071-4ab2c5d273f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mui-45']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@name = 'url']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mui-45</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>94d488e6-65d6-49ee-b742-8563acf7bd97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f6fd1e8f-e4ea-4230-afb1-eadd5a38893a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>url</value>
      <webElementGuid>5713caa2-15c5-4212-b3fa-a0c74ff90703</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>https://github.com/ardionoroma/DVSA.git</value>
      <webElementGuid>804c65a5-5df5-403c-81a7-82b2f8302d36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>50215873-776d-4eb4-bb34-88984434f9f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input css-pb771q-MuiInputBase-input-MuiOutlinedInput-input</value>
      <webElementGuid>43901891-813d-490e-a4b5-43b53bc197d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mui-45</value>
      <webElementGuid>324e52b9-fd81-413e-b766-bcb8fc0f726b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mui-45&quot;)</value>
      <webElementGuid>f51a7290-1dc9-44f9-9f11-96b16f9a35d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mui-45']</value>
      <webElementGuid>79c41fad-b40f-4177-8212-22e61fb0b1a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div/div/div/div[3]/div/div/div/div/div/div[2]/div/div[4]/div/div/input</value>
      <webElementGuid>de7e2804-a9af-43b7-8e7b-9e94209e2264</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>4d20e8a6-535c-4d9f-acdd-b5294a1eaf54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'url' and @placeholder = 'https://github.com/ardionoroma/DVSA.git' and @type = 'text' and @id = 'mui-45']</value>
      <webElementGuid>8032814d-02ec-484f-b933-be6b5bf175df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
