<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input Repo url</name>
   <tag></tag>
   <elementGuidId>f97377d9-9fc9-4a6d-9d90-1a905404da46</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mui-47']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mui-47</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b4e9e819-5930-45d2-b8ec-6706554cb50c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>374037bb-2409-4e6d-b9dc-905966a39402</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>url</value>
      <webElementGuid>1c622c2f-ab8b-42ef-bdc3-004b1824e70a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>http://github.com/repo.git</value>
      <webElementGuid>14469a54-3c06-4a8c-a6e5-13d4fc8cd2b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9a0c45ad-df18-49d3-a7d1-32e1e572b387</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiOutlinedInput-input MuiInputBase-input css-pb771q-MuiInputBase-input-MuiOutlinedInput-input</value>
      <webElementGuid>9b74c223-0855-4f35-b7bd-922a340ec44c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mui-47</value>
      <webElementGuid>e1c0c968-bdfa-4090-bd04-fc97ea50de7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mui-47&quot;)</value>
      <webElementGuid>8bb64083-0d2f-4ece-aab8-375244ce1731</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mui-47']</value>
      <webElementGuid>c8caa682-3457-4c49-9971-c0b6a41a58a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div/div/div/div[3]/div/div/div/div/div/div[2]/div/div[4]/div/div/input</value>
      <webElementGuid>9f5e2dac-1288-4e0d-ba8e-2a5d66ed56d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>07cc52a6-a25f-43d4-922f-4623a39f1989</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'url' and @placeholder = 'http://github.com/repo.git' and @type = 'text' and @id = 'mui-47']</value>
      <webElementGuid>6a3d213e-9c56-4008-a0a1-47015a57cfbc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
