<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input-UsernameField</name>
   <tag></tag>
   <elementGuidId>b45c810e-90d4-43e6-96db-4fdc5fb7421d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@name = 'username_field']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mui-33']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mui-33</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7d42925b-f044-4741-954d-36b2e217e0ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>803d539e-5ff3-40f7-b8e9-48beea531a42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>username_field</value>
      <webElementGuid>2cd883d1-12c7-4478-b87d-1ae36c0c800c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>e.g. username</value>
      <webElementGuid>bf21c324-76cf-4f8e-a1f0-d7e3c4c5d778</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7c68a7ea-0446-490b-b013-728dc780d1b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input css-gc8fv7</value>
      <webElementGuid>12fe2bd5-10d4-43e1-ac5b-f0cb55aa88fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mui-33</value>
      <webElementGuid>89d51303-e0c7-4ec2-9acf-39782915ba38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mui-33&quot;)</value>
      <webElementGuid>6acffc5f-de07-4260-ae60-9962136723f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mui-33']</value>
      <webElementGuid>6b483661-b23c-48c1-8594-3b741277099c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/input</value>
      <webElementGuid>68162f17-3035-4724-bb2b-2232d8ad7591</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'username_field' and @placeholder = 'e.g. username' and @type = 'text' and @id = 'mui-33']</value>
      <webElementGuid>44090c79-aae3-42ef-8d08-2f12e73c1c5f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
