<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input-SubmitField</name>
   <tag></tag>
   <elementGuidId>06f2adfc-3b50-45a4-849b-45f72fc5281d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@name = 'submit_field']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mui-32']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mui-32</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d08595fa-5320-4f8e-8603-4f7018957c2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>304269f8-e2f0-4291-809c-5e7658e58142</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>submit_field</value>
      <webElementGuid>c91eed24-d685-4c41-af11-a388488256f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fc6f2873-6081-4743-9fd9-1349c3cf7082</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input css-1e8usrf</value>
      <webElementGuid>4bfec6f0-883f-4bcf-9df8-c9fbff842016</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mui-32</value>
      <webElementGuid>25ede32e-578a-4152-99de-c5ce11830ddc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mui-32&quot;)</value>
      <webElementGuid>b8385919-f062-4be9-ace9-b8bd76448834</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mui-32']</value>
      <webElementGuid>9598661d-e6d4-49f5-9050-79693a917840</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/div/input</value>
      <webElementGuid>b0ccff8d-0f6b-452f-b366-98df0fcaf1b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'submit_field' and @type = 'text' and @id = 'mui-32']</value>
      <webElementGuid>4ea28c3c-3961-4e94-b149-80b2204f7941</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
